name: Create releases
on:
  release:
    types: [published]
jobs:
  update-heroku-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          TASKING_ENV: PROD
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
          DATABASE_USERNAME_TEST: ${{ secrets.DATABASE_USERNAME_TEST }}
          DATABASE_PASSWORD_TEST: ${{ secrets.DATABASE_PASSWORD_TEST }}
          DATABASE_NAME_TEST: ${{ secrets.DATABASE_NAME_TEST }}
